const ORDER_SIDE = {
  BUY: 'BUY',
  SELL: 'SELL',
}

const ORDER_STATUS = {
  PENDING: 'PENDING',
  MATCHING: 'MATCHING',
  // PARTIALLY_MATCHING: 'PARTIALLY_MATCHING', // TODO think over maybe we need it one day
  CANCELED: 'CANCELED',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FULL_FILLED: 'FULL_FILLED',
}

const SUPPORTED_ORDER_VERSION = 2
const CONTRACT_GAS = 190000

module.exports = {
  ORDER_SIDE,
  ORDER_STATUS,
  SUPPORTED_ORDER_VERSION,
  CONTRACT_GAS,
}
